import React, { useEffect, useRef, useState } from "react";
import { base44 } from "@/api/base44Client";
import { Sparkles, Loader2, Image as ImageIcon, Check, Tag } from "lucide-react";
import {
  parseBidSentence,
  buildBid,
  applyDiscount,
  bidToText,
  money,
  TERMS_TEXT,
  WARRANTY_TEXT,
} from "@/lib/bidEngine";
import JobSitePhotos from "@/components/bid/JobSitePhotos";
import BidShareBar from "@/components/bid/BidShareBar";

const EXAMPLES = [
  "Metallic epoxy floor for a 2-car garage, 500 sq ft, fair condition, with some cracks and a few spalls",
  "Flake epoxy for a 1200 sq ft showroom, silver gray, high gloss, with expansion joints",
  "Polished concrete for a 3000 sq ft warehouse, good condition, lots of joint fill",
];

export default function BidGenerator() {
  const [sentence, setSentence] = useState("");
  const [generating, setGenerating] = useState(false);
  const [bid, setBid] = useState(null);
  const [discountPct, setDiscountPct] = useState(0);
  const [err, setErr] = useState("");
  const [floorSystems, setFloorSystems] = useState([]);
  const [colorCharts, setColorCharts] = useState([]);
  const [user, setUser] = useState(null);
  const [photos, setPhotos] = useState([]);
  const [savedToCrm, setSavedToCrm] = useState(false);
  const [logoUploading, setLogoUploading] = useState(false);
  const logoRef = useRef(null);

  useEffect(() => {
    base44.entities.FloorSystem.list("-created_date", 100).then(setFloorSystems).catch(() => {});
    base44.entities.ColorChart.list("-created_date", 200).then(setColorCharts).catch(() => {});
    base44.auth.me().then(setUser).catch(() => {});
  }, []);

  const logoUrl = user?.logo_url || "";

  const generate = async () => {
    if (!sentence.trim()) return;
    setGenerating(true);
    setErr("");
    setSavedToCrm(false);
    try {
      const parsed = await parseBidSentence(sentence, floorSystems, colorCharts);
      const built = buildBid(parsed, floorSystems, colorCharts);
      const withDiscount = applyDiscount(built, discountPct);
      setBid(withDiscount);
      saveToCrm(withDiscount, parsed);
    } catch (e) {
      setErr("Could not generate bid. " + (e.message || ""));
    } finally {
      setGenerating(false);
    }
  };

  const saveToCrm = async (built, parsed) => {
    try {
      await base44.entities.Lead.create({
        customer_name: built.customer_name || "Bid Generator lead",
        email: "",
        phone: "",
        project_address: built.project_address,
        space_type: "garage",
        floor_type: built.floor_type,
        system_name: built.floor_type,
        color_name: built.color_name,
        color_hex: built.color_hex,
        finish: built.finish,
        square_feet: built.square_feet,
        condition: built.condition,
        needs_grinding: parsed.needs_grinding,
        needs_moisture_mitigation: parsed.needs_moisture_mitigation,
        linear_feet_cracks: parsed.linear_feet_cracks || 0,
        linear_feet_joints: parsed.linear_feet_joints || 0,
        linear_feet_coving: parsed.linear_feet_coving || 0,
        patch_count: parsed.patch_count || 0,
        excessive_patch_count: parsed.excessive_patch_count || 0,
        large_patch_count: parsed.large_patch_count || 0,
        demolition_sqft: parsed.demolition_sqft || 0,
        extra_prep: parsed.extra_prep || false,
        estimate_low: built.subtotal,
        estimate_high: built.subtotal,
        proposal_total: built.total,
        discount_amount: built.discount_amount || 0,
        discount_pct: built.discount_pct || 0,
        floor_logo_description: built.logo_description,
        source: "manual",
        status: "new",
        notes: `Generated by AI Bid Generator.${photos.length ? ` Photos: ${photos.join(", ")}` : ""}`,
      });
      setSavedToCrm(true);
    } catch (e) {
      // bid still shown
    }
  };

  const onDiscount = (pct) => {
    setDiscountPct(pct);
    if (bid) setBid(applyDiscount(bid, pct));
  };

  const uploadLogo = async (file) => {
    if (!file) return;
    setLogoUploading(true);
    try {
      const { file_url } = await base44.integrations.Core.UploadFile({ file });
      if (file_url) {
        await base44.auth.updateMe({ logo_url: file_url });
        setUser({ ...user, logo_url: file_url });
      }
    } catch (e) {}
    setLogoUploading(false);
  };

  const bidText = bid ? bidToText(bid) : "";

  return (
    <div className="page hx-page">
      <div className="hx-page-head">
        <div>
          <h1>
            AI <span style={{ color: "var(--vx-accent)" }}>Bid Generator</span>
          </h1>
          <p>Describe the job in one sentence. We'll build a complete bid — scope, pricing, terms, and warranty — in seconds.</p>
        </div>
      </div>

      <div className="hx-bid-input-card">
        <textarea
          className="hx-bid-textarea"
          rows={3}
          placeholder="e.g. Metallic epoxy floor for a 2-car garage, 500 sq ft, fair condition, with some cracks and a few spalls"
          value={sentence}
          onChange={(e) => setSentence(e.target.value)}
        />
        <div className="hx-bid-examples">
          {EXAMPLES.map((ex, i) => (
            <button key={i} className="hx-bid-example-chip" onClick={() => setSentence(ex)}>
              {ex.length > 46 ? ex.slice(0, 46) + "…" : ex}
            </button>
          ))}
        </div>
        <button
          className="hx-mini-btn"
          onClick={generate}
          disabled={generating || !sentence.trim()}
          style={{ width: "100%", justifyContent: "center", minHeight: 48 }}
        >
          {generating ? <Loader2 size={18} className="spin" /> : <Sparkles size={18} />}
          <span>{generating ? "Generating bid..." : "Generate Bid"}</span>
        </button>
      </div>

      {err && <p style={{ color: "var(--vx-danger)", fontSize: 12 }}>{err}</p>}

      {bid && (
        <>
          {savedToCrm && (
            <div className="hx-bid-saved">
              <Check size={14} /> Saved to CRM automatically
            </div>
          )}

          <div className="hx-bid-controls">
            <div className="hx-bid-discount">
              <Tag size={16} />
              <span style={{ fontSize: 12, color: "#A0A0A0" }}>Discount %</span>
              <input
                type="number"
                min="0"
                max="50"
                value={discountPct}
                onChange={(e) => onDiscount(e.target.value)}
              />
              <span style={{ fontSize: 12, color: "var(--vx-accent)", fontWeight: 700 }}>
                {money(bid.discount_amount)}
              </span>
            </div>
            <div className="hx-bid-logo-row">
              {logoUrl && <img src={logoUrl} alt="Logo" style={{ height: 36, maxWidth: 120, objectFit: "contain" }} />}
              <input
                ref={logoRef}
                type="file"
                accept="image/*"
                onChange={(e) => uploadLogo(e.target.files?.[0])}
                className="hidden"
              />
              <button
                className="hx-bid-logo-btn"
                onClick={() => logoRef.current?.click()}
                disabled={logoUploading}
              >
                {logoUploading ? <Loader2 size={14} className="spin" /> : <ImageIcon size={14} />}
                <span>{logoUrl ? "Change logo" : "Add logo"}</span>
              </button>
            </div>
          </div>

          <div className="hx-bid-doc">
            <div className="hx-bid-doc-head">
              <div className="hx-bid-meta">
                <span className="hx-bid-title">Proposal</span>
                {logoUrl ? (
                  <img src={logoUrl} alt="Logo" className="hx-bid-logo" />
                ) : (
                  <strong className="hx-bid-company">Xtreme Polishing Systems</strong>
                )}
              </div>
              <span style={{ fontSize: 11, color: "#A0A0A0" }}>
                {new Date(bid.created_date).toLocaleDateString()}
              </span>
            </div>

            <div className="hx-bid-meta">
              <strong>{bid.customer_name || "Valued Customer"}</strong>
              {bid.project_address && <span>{bid.project_address}</span>}
            </div>

            <div className="hx-bid-section">
              <h3>Project</h3>
              <p style={{ margin: 0, fontSize: 12, color: "#fff" }}>
                {bid.floor_type} — {bid.square_feet.toLocaleString()} sq ft ({bid.condition} condition)
              </p>
              {(bid.color_name || bid.finish) && (
                <p style={{ margin: "2px 0 0", fontSize: 11, color: "#A0A0A0" }}>
                  {[bid.color_name, bid.finish].filter(Boolean).join(" • ")}
                </p>
              )}
              {bid.logo_description && (
                <p style={{ margin: "2px 0 0", fontSize: 11, color: "#A0A0A0" }}>
                  Floor logo: {bid.logo_description}
                </p>
              )}
            </div>

            <div className="hx-bid-section">
              <h3>Scope of Work</h3>
              <div className="hx-bid-scope">
                {bid.scope_items.map((s, i) => (
                  <div key={i} className="hx-bid-scope-item">
                    <strong>{s.label}</strong>
                    <span>{s.detail}</span>
                  </div>
                ))}
              </div>
            </div>

            <div className="hx-bid-section">
              <h3>Investment</h3>
              <div className="hx-bid-lines">
                {bid.line_items.map((li, i) => (
                  <div key={i} className="hx-bid-line">
                    <div>
                      <div className="hx-bid-line-name">{li.name}</div>
                      <div className="hx-bid-line-detail">{li.detail}</div>
                    </div>
                    <div className="hx-bid-line-amt">{money(li.amount)}</div>
                  </div>
                ))}
              </div>
              <div className="hx-bid-totals" style={{ marginTop: 10 }}>
                <div className="hx-bid-totals-row">
                  <span>Subtotal</span>
                  <span>{money(bid.subtotal)}</span>
                </div>
                {bid.discount_amount > 0 && (
                  <div className="hx-bid-totals-row">
                    <span>Discount ({bid.discount_pct}%)</span>
                    <span>-{money(bid.discount_amount)}</span>
                  </div>
                )}
                <div className="hx-bid-totals-row total">
                  <span>Total</span>
                  <span>{money(bid.total)}</span>
                </div>
              </div>
            </div>

            {photos.length > 0 && (
              <div className="hx-bid-section">
                <h3>Job Site Photos</h3>
                <div className="hx-bid-photo-grid">
                  {photos.map((url, i) => (
                    <div key={i} className="hx-bid-photo-tile">
                      <img src={url} alt={`Site ${i + 1}`} />
                    </div>
                  ))}
                </div>
              </div>
            )}

            <div className="hx-bid-terms">
              <h4>Terms &amp; Conditions</h4>
              <p>{TERMS_TEXT}</p>
              <h4>Warranty</h4>
              <p>{WARRANTY_TEXT}</p>
            </div>
          </div>

          <JobSitePhotos photos={photos} setPhotos={setPhotos} />

          <BidShareBar bidText={bidText} />
        </>
      )}
    </div>
  );
}